version: '3.8'

services:
  demo-notion-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # ใช้ build stage สำหรับ development
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=debug
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    working_dir: /app
    command: go run main.go
    restart: unless-stopped

volumes:
  go-mod-cache: